### ISSUE TITLE
Error with 0d entities

### ISSUE THREAD

**Issue by figorr** [cytech/Home-Assistant-wundergroundpws#210] opened 2023-10-09 06:35 UTC
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
**Describe the bug**

I installed the integration yesterday afternoon, so the 0d values were not available yet by then. But today, after the data was refreshed … the sensor “sensor.ivalli36_forecast_temperature_0d” is showing the error that this entity has no class and the correct unit of measurement. All the others forecast temperature entities had ºC as the unit of measurement but the 0d didn’t show any unit.

A similar error with the sensor “sensor.ivalli36_forecast_summary_0d”. In this case …  ValueError: could not convert string to float.

**To Reproduce**
1. Install the integration at the afternoon.

**Expected behavior**
I expected not errors at 0d entities.

**Screenshots**

![IMG_0325](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/77553975/08d77743-1c6d-498d-9cc4-63395a8f9003)

![IMG_0326](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/77553975/64327182-1ccb-4e80-9cde-c78f47727c4e)

![IMG_0327](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/77553975/813ab3e1-6b83-4269-927b-5cbbbfa1e150)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version : 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 17.0.3
 - Browser: Safari
 - Version: default

**Additional context**

**Comment by cytech** [comment] 2023-12-14 17:29
duplicate of issue https://github.com/cytech/Home-Assistant-wundergroundpws/issues/211

**Closed by cytech** 2023-12-14 17:29 UTC
