### ISSUE TITLE
 non-numeric log entries with forecast_summary

### ISSUE THREAD

**Issue by genem2** [cytech/Home-Assistant-wundergroundpws#211] opened 2023-10-19 19:54 UTC
**Describe the bug**
All of a sudden, the log is filling again with  non-numeric value errors regarding forecast_summary entities.

**To Reproduce**
1. Not sure - this just started about 24hrs now

**Expected behavior**
No log entries

**Screenshots**
```
2023-10-19 12:41:48.901 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 593, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'Plentiful sunshine. Near record high temperatures. High 97F. Winds NW at 5 to 10 mph.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/config/custom_components/wundergroundpws/sensor.py", line 200, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 595, in state
    raise ValueError(
ValueError: Sensor sensor.kcasanjo1654_forecast_summary_0d has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Plentiful sunshine. Near record high temperatures. High 97F. Winds NW at 5 to 10 mph.' (<class 'str'>)

```
FWIW, The log is suggesting an issue with **forecast_summary_0d**, but the non-numeric value
`ValueError: could not convert string to float: 'Plentiful sunshine.... `
is from **summary_2d**.  Does that offer a clue?

| entity | FriendlyName | state |
| ----- | --------- | ------------------|
| sensor.kcasanjo1654_forecast_summary_0d |  Forecast Summary Today Expired |  unknown
| sensor.kcasanjo1654_forecast_summary_1n |  Forecast Summary Tonight |  A clear sky. Low 64F. Winds light and variable
| sensor.kcasanjo1654_forecast_summary_2d |  Forecast Summary Tomorrow | Mainly sunny. Near record high temperatures. High 98F. Winds NW at 5 to 10 mph.
| sensor.kcasanjo1654_forecast_summary_3n  |  Forecast Summary Tomorrow night |  A few clouds. Low 61F. Winds light and variable.

**Desktop (please complete the following information):**
 - OS: 
## System Information

version | core-2023.10.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.49-Unraid
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1325
Downloaded Repositories | 39

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 25
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 5, 2023 at 6:02 PM
-- | --
current_recorder_run | October 18, 2023 at 4:16 PM
estimated_db_size | 51.57 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.3 (a8c6d45)
-- | --
cloud_online | 11 / 15
local_online | 11 / 11

</details>

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
 - [EDIT]:    Wundergroundpws version: 2.0.4

**Comment by RJ-Make** [comment] 2023-10-24 11:32
I'm seeing the **_exact_** same problem, with the same version. I just moved from 1.x version to 2.x 2 weeks ago and notices after a short time "x_forecast_summary_0d = Forecast Summary Today Expired (unknown)".  

If I restart the PI, it starts working for a period of time.

**Comment by denispelo** [comment] 2023-10-27 13:31
Hi, I've the same issue as yours. After a restart of supervisor, it's work for a while, but after stopped.

**Comment by RJ-Make** [comment] 2023-12-09 21:23
Any movement on this problem. Today forecast (x_forecast_summary_0d) is foobared for me in V2.x? 

What can I provide to help source the cause.

**Comment by cytech** [comment] 2023-12-14 17:54
i cannot duplicate this in 2023.12 with wupws 2.0.4.
i have seen it in the past due to some erroneous value returned by the API.
it has always corrected itself after some amount of time.
i am going to assume this is the case with this report and close it, as there has been no follow up to the status.
"All of a sudden, the log is filling again with non-numeric value errors regarding forecast_summary entities."
the all of a sudden comment points the finger at the API response...

**Closed by cytech** 2023-12-14 17:54 UTC
