### ISSUE TITLE
New warning

### ISSUE THREAD

**Issue by fowlermusic** [cytech/Home-Assistant-wundergroundpws#235] opened 2024-02-26 14:58 UTC
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
**Describe the bug**
This stops working in version 2024.3.0. Please address before upgrading.
The custom integration wundergroundpws implements the forecast property or sets self._attr_forecast in a subclass of WeatherEntity.

Please create a bug report at https://github.com/cytech/Home-Assistant-wundergroundpws/issues/.

Once an updated version of wundergroundpws is available, install it and restart Home Assistant to fix this issue.

**Comment by cytech** [comment] 2024-03-14 20:30
duplicate of issue #230
upgrade to wundergroundpws 2.0.6

**Closed by cytech** 2024-03-14 20:30 UTC
